Users bets
Karbowskii/zzpj pull request #32
Opened 2020-06-08 12:56 UTC by piotr3290

2020-06-09 20:43 UTC, ZielaA requested changes

2020-06-09 20:43 UTC, ZielaA commented on frontend/src/components/BettingModal.vue
> +                    <!--                    <div class="text-center stake">Stake is x{{betStake.toFixed(2)}}</div>-->
Pliska, usunąć nieużywany zakomentowany kod

2020-06-09 20:43 UTC, ZielaA commented on backend/src/main/java/pl/zzpj/esportbetting/rest/UserRestController.java
> +        return ResponseEntity.ok("\"User successfully created!\"");
Ta zmiana jest na pewno potrzebna?

2020-06-09 20:43 UTC, ZielaA commented
Działa bardzo fajnie. Uwagi takie jak u Michała, czyli aplication.properties i modyfikacja testów.

2020-06-10 16:14 UTC, piotr3290 commented on backend/src/main/java/pl/zzpj/esportbetting/rest/UserRestController.java
> +        return ResponseEntity.ok("\"User successfully created!\"");
Jak nie było cudzysłowu to na froncie nie widziało odpowiedzi i łapało błąd.

2020-06-10 16:16 UTC, piotr3290 commented on frontend/src/components/BettingModal.vue
> +                    <!--                    <div class="text-center stake">Stake is x{{betStake.toFixed(2)}}</div>-->
Tu ma być wyświetlany przelicznik jak będzie się obstawiać, ale były różne dyskusje jak to ma wyglądać to zakomentowałem, ale będzie można go użyć.

2020-06-11 16:29 UTC, Karbowskii approved these changes

2020-06-11 16:29 UTC, merged